<a href="https://colab.research.google.com/github/Affra003/1234/blob/main/genNUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.arange(10)
print("The array over the given range is ",arr)


The array over the given range is  [0 1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy as np
arr = np.arange(0,10,2,float)
print(arr)


[0. 2. 4. 6. 8.]


In [ ]:
import numpy as np
arr = np.arange(10,100,5,float)
print("The array over the given range is ",arr)

The array over the given range is  [10. 15. 20. 25. 30. 35. 40. 45. 50. 55. 60. 65. 70. 75. 80. 85. 90. 95.]


In [ ]:
# give non predictiable value -- used in generating otp
import numpy as np

x = np.random.rand(10)# one dimension array

print(x)


[0.56872097 0.37148265 0.23311521 0.04998046 0.30975733 0.1509896
 0.04457741 0.84852126 0.95708804 0.29911905]


In [ ]:
import numpy as np

x = np.random.rand(100)# one dimension array

print(x)

[0.24963677 0.91295735 0.34486284 0.42785024 0.97284622 0.54205146
 0.87744423 0.25512538 0.48547382 0.60696462 0.28445905 0.76447305
 0.6403161  0.02031669 0.19185746 0.71904989 0.65862328 0.63419439
 0.23949792 0.24944474 0.30421956 0.22805657 0.65386314 0.34072325
 0.15718177 0.40496164 0.33366923 0.85618729 0.92204512 0.86386186
 0.25714337 0.64748054 0.17829629 0.1911092  0.92158164 0.90895368
 0.08767731 0.06084471 0.00345163 0.81160105 0.53250423 0.71944939
 0.10686253 0.68627525 0.78884403 0.42907984 0.25982092 0.9855882
 0.90900668 0.48203825 0.3561321  0.43510583 0.63537357 0.39640064
 0.13200218 0.03080402 0.23309641 0.09448613 0.40302192 0.0087331
 0.71994339 0.20820707 0.02463329 0.06850351 0.98341723 0.73930262
 0.04858951 0.65832992 0.43019577 0.22651098 0.70336487 0.6737292
 0.27363633 0.89705658 0.12574076 0.68348099 0.84958468 0.90680873
 0.0390671  0.58507335 0.38205389 0.02186623 0.90478309 0.86255521
 0.28046255 0.64157505 0.43132325 0.30138318 0.32770946 0.6828843

In [ ]:
#Shuffle
from numpy import random
import numpy as np

a= np.array([1, 2, 3, 4, 5])

random.shuffle(a)

print(a)


[5 2 4 3 1]


In [ ]:
#REMOVE
from numpy import random
import numpy as np

a= np.array([1, 2, 3, 4, 5])
a=a.tolist()
a.remove(4)
a=np.array(a)
print(a)



[1 2 3 5]


In [ ]:
import numpy as np

x = np.random.rand(10)# one dimension array
random.shuffle(x)
print(x)
a=x*10003
print(a)
r=np.round(a,0)
print(r)


[0.91401262 0.56911497 0.18074464 0.58777979 0.11843196 0.60571009
 0.84391386 0.59180826 0.38387078 0.19645949]
[9142.86828649 5692.8570853  1807.98866928 5879.56121224 1184.67490507
 6058.91802179 8441.67036479 5919.85800407 3839.85940207 1965.18426019]
[9143. 5693. 1808. 5880. 1185. 6059. 8442. 5920. 3840. 1965.]


In [ ]:
#important concept (probability)
from numpy import random

x = random.choice([3.5, 5.7, 7.9, 9.3], p=[0.1, 0.8, 0.0, 0.1], size=(100))

print(x)


[5.7 5.7 5.7 5.7 5.7 3.5 5.7 5.7 5.7 9.3 5.7 5.7 9.3 5.7 5.7 5.7 5.7 5.7
 9.3 9.3 5.7 5.7 5.7 5.7 5.7 5.7 5.7 5.7 5.7 5.7 5.7 5.7 5.7 5.7 5.7 5.7
 3.5 5.7 5.7 5.7 5.7 5.7 5.7 5.7 5.7 5.7 5.7 5.7 5.7 5.7 5.7 3.5 5.7 3.5
 5.7 5.7 5.7 5.7 5.7 5.7 5.7 5.7 3.5 3.5 5.7 3.5 5.7 5.7 5.7 5.7 9.3 5.7
 5.7 5.7 5.7 9.3 5.7 9.3 9.3 5.7 5.7 5.7 5.7 5.7 5.7 9.3 9.3 5.7 9.3 5.7
 5.7 9.3 5.7 5.7 5.7 5.7 5.7 9.3 5.7 5.7]


In [ ]:
#random Excel creation
import numpy as np
from numpy import random
import pandas as pd

arr = ['Arun', 'Akash', 'Sanjay', 'Manu']
a=np.random.choice(arr, 1500, p=[0.5, 0.1, 0.1, 0.3])
b = random.choice([30, 52, 72, 91,80,60], p=[0.1, 0.2, 0.3, 0.1,0.1,0.2], size=(1500))
c = random.choice([30, 52, 72, 91,80,60], p=[0.1, 0.2, 0.3, 0.1,0.1,0.2], size=(1500))
d = random.choice([30, 52, 72, 91,80,60], p=[0.1, 0.2, 0.3, 0.1,0.1,0.2], size=(1500))
e = random.choice([30, 52, 72, 91,80,60], p=[0.1, 0.2, 0.3, 0.1,0.1,0.2], size=(1500))
f = random.choice([30, 52, 72, 91,80,60], p=[0.1, 0.2, 0.3, 0.1,0.1,0.2], size=(1500))

frame={"Name":a, "M1":b, "M2":b, "M3":c,"M4":d,"M5":e,"M6":f}
df=pd.DataFrame(frame)
print(df)
df.to_excel('mark.xlsx', index=False)

        Name  M1  M2  M3  M4  M5  M6
0       Manu  30  30  72  91  60  80
1       Manu  72  72  72  30  72  60
2       Arun  80  80  30  72  52  80
3      Akash  52  52  52  80  72  91
4       Arun  60  60  91  80  52  60
...      ...  ..  ..  ..  ..  ..  ..
1495    Manu  60  60  72  52  52  60
1496  Sanjay  52  52  72  52  60  52
1497    Arun  80  80  60  72  52  72
1498    Manu  60  60  72  72  72  52
1499    Arun  72  72  52  72  91  72

[1500 rows x 7 columns]


In [ ]:
#random Excel creation
import numpy as np
from numpy import random
import pandas as pd

arr = ['A', 'B', 'C', 'D']
# The size for 'a' should be the same as the other columns (2500)
a = np.random.choice(arr, 2500, p=[0.5, 0.1, 0.1, 0.3])
b = random.choice([0.91401262, 0.56911497 ,0.18074464, 0.58777979, 0.11843196, 0.60571009], p=[0.1, 0.2, 0.3, 0.1,0.1,0.2], size=(2500))
c = random.choice([9142.86828649, 5692.8570853,  1807.98866928, 5879.56121224 ,1184.67490507, 6058.91802179], p=[0.1, 0.2, 0.3, 0.1,0.1,0.2], size=(2500))
d = random.choice([30, 52, 72, 91,80,60], p=[0.1, 0.2, 0.3, 0.1,0.1,0.2], size=(2500))
e = random.choice([30, 52, 72, 91,80,60], p=[0.1, 0.2, 0.3, 0.1,0.1,0.2], size=(2500))
f = random.choice([30, 52, 72, 91,80,60], p=[0.1, 0.2, 0.3, 0.1,0.1,0.2], size=(2500))

frame={"Name":a, "M1":b, "M2":b, "M3":c,"M4":d,"M5":e,"M6":f}
df=pd.DataFrame(frame)
print(df)
df.to_excel('mark.xlsx', index=False)

     Name        M1        M2           M3  M4  M5  M6
0       A  0.914013  0.914013  1807.988669  72  52  60
1       A  0.914013  0.914013  5879.561212  60  30  72
2       A  0.569115  0.569115  1807.988669  52  52  72
3       C  0.180745  0.180745  5692.857085  91  80  30
4       C  0.605710  0.605710  1184.674905  72  52  72
...   ...       ...       ...          ...  ..  ..  ..
2495    A  0.118432  0.118432  1807.988669  72  80  72
2496    D  0.118432  0.118432  9142.868286  91  72  72
2497    D  0.180745  0.180745  1184.674905  52  91  52
2498    A  0.180745  0.180745  1807.988669  30  30  72
2499    A  0.587780  0.587780  9142.868286  72  72  72

[2500 rows x 7 columns]


In [ ]:
#rng used to suffle
import numpy as np
# Initialize random number generator
rng = np.random.default_rng()
# Generate random integers between 1 and 2 (inclusive)
num_records = 10
random_numbers = rng.integers(1, 3, size=num_records)
print(random_numbers)

[1 2 2 1 2 2 1 1 2 2]


In [ ]:
##uniform method in rng
#float cant be given
import numpy as np
# Initialize random number generator
rng = np.random.default_rng()
# Generate random floating-point numbers between 1 and 3
num_records = 10
random_numbers = rng.uniform(1, 3, size=num_records)
print(random_numbers)

[2.95725172 2.34678904 1.73761024 2.11911505 1.1710832  1.24479651
 2.09846354 1.11048074 1.62911201 1.74515977]


In [ ]:
#choice
import numpy as np# Generate 10 unique random integers between 1 and 100
# Initialize random number generator
rng = np.random.default_rng()
# Generate 10 unique random integers between 1 and 100
num_records = 10
unique_integers = rng.choice(np.arange(1, 101), size=num_records, replace=False)
print(unique_integers)

[ 83  80  23  74  78  66  90 100  81  37]


In [ ]:
#names
import numpy as np
# Initialize random number generator
rng = np.random.default_rng()
# List of sample names
name_list = ["John", "Alice",  "Sophia", "Liam", "Emma", "Noah", "Olivia", "James", "Mia"]
# Number of names to generate
num_records = 200
# Generate random names by selecting from the name_list
random_names = rng.choice(name_list, size=num_records, replace=True)
# Print the random names
print(random_names)

['Sophia' 'John' 'Noah' 'John' 'Noah' 'Alice' 'Sophia' 'John' 'Sophia'
 'Alice' 'Alice' 'Noah' 'Emma' 'John' 'Emma' 'Mia' 'James' 'Emma' 'Emma'
 'John' 'Emma' 'Noah' 'Emma' 'John' 'Emma' 'Noah' 'Alice' 'Emma' 'Sophia'
 'Sophia' 'Noah' 'James' 'Liam' 'Olivia' 'Alice' 'Mia' 'Mia' 'James'
 'Sophia' 'Mia' 'Mia' 'John' 'Sophia' 'Alice' 'James' 'Alice' 'James'
 'James' 'Liam' 'Sophia' 'Noah' 'Noah' 'Mia' 'James' 'John' 'Noah' 'James'
 'Alice' 'Emma' 'Mia' 'Emma' 'Alice' 'Mia' 'Mia' 'John' 'James' 'Liam'
 'Alice' 'Mia' 'Mia' 'James' 'John' 'James' 'Olivia' 'John' 'Noah' 'Liam'
 'Alice' 'Noah' 'Alice' 'Alice' 'Emma' 'Sophia' 'Sophia' 'Olivia' 'Sophia'
 'Mia' 'Liam' 'Sophia' 'Olivia' 'John' 'John' 'Olivia' 'Sophia' 'Olivia'
 'Alice' 'Alice' 'Noah' 'James' 'James' 'Olivia' 'James' 'Emma' 'Emma'
 'Olivia' 'Emma' 'Noah' 'John' 'James' 'Emma' 'Mia' 'Emma' 'Noah' 'Olivia'
 'John' 'Alice' 'Liam' 'John' 'James' 'Mia' 'Olivia' 'Liam' 'Mia' 'Liam'
 'Emma' 'Mia' 'Emma' 'Olivia' 'Emma' 'Sophia' 'Alice' 'L

In [ ]:
#ML sales 15 data
import numpy as np
from numpy import random
import pandas as pd
def name():
    arr = ['Arun', 'Akash', 'Sanjay', 'Manu']
    n=np.random.choice(arr, 15, p=[0.5, 0.1, 0.1, 0.3])
    return n
def month():
    m1 = random.choice([1,2,3,4,5,6,7,8,9,10,11,12], p=[0.1, 0.1, 0.1, 0.1,0.1,0.1,0.1, 0.1, 0.05, 0.05,0.05,0.05], size=(15))
    return m1
def id():
    id = np.arange(15)
def unitprice():
     x = np.random.rand(15)
     x1=x*1000
     unit = np.round(x1, decimals=0)
     return unit
def quan():
    y = random.uniform(size=(15))
    y1=y*100
    q = np.round(y1, decimals=0)
    return q
def location():
    country_names = ["USA", "Canada", "UK", "Germany", "France", "Japan", "Australia"]
    c=np.random.choice(country_names, 15, p=[0.3, 0.1, 0.1, 0.1,0.1,0.1,0.2])
    return c
def coustomerid():
    z = np.arange(300, 320)
    x = random.choice(z, p=[0.05]*len(z), size=(15))
    return x
def prodid():
    y = random.uniform(size=(15))
    y1=y*100
    p = np.round(y1, decimals=2)
    np.random.shuffle(p)
    return p
def storeid():
    z = np.arange(1300, 1320)
    x = random.choice(z, p=[0.05]*len(z), size=(15))
    return x
def storesize():
    arr = ['Premium', 'Branded', 'Valueformoney', 'Economy','Sale','Factoryoutlet','Retail']
    n=np.random.choice(arr, 15, p=[0.2, 0.1, 0.1, 0.2,0.1,0.2,0.1])
    return n
def closetime():
    ohrs1 = random.choice([21,22,23,20], p=[0.2, 0.2, 0.2, 0.4], size=(15))
    return ohrs1
def adv():#advertise rating star
    adv=random.choice([1,2,3,4,5], p=[0.2, 0.2, 0.2, 0.2,0.2], size=(15))
    return adv

def com():#competetor price
    com=random.choice(["High","Low","Equal"], p=[0.2, 0.2, 0.6], size=(15))
    return com
def sup():#supply
    sup=random.choice(["Surplus","LowStock","StockAvailable"], p=[0.2, 0.2, 0.6], size=(15))
    return sup
def paytype():
    pay=random.choice(["CreditCard","DebitCard","Cash","UPI","EMI"], p=[0.4, 0.1, 0.1,0.1,0.3], size=(15))
    return pay
def profit():#profit in per
    profit=random.choice([10,15,5,20,25], p=[0.4, 0.1, 0.1,0.1,0.3], size=(15))
    return profit
def feedback():
    feed=random.choice([1,2,3,4,5], p=[0.2, 0.2, 0.2, 0.2,0.2], size=(15))
    return feed

def infra():
    infra=random.choice(["Own","Rented", "Sponsored"], p=[0.2, 0.5, 0.3], size=(15))
    return infra
def parking():
    park=random.choice(["Spacious","Available", "NotAvailable"], p=[0.2, 0.5, 0.3], size=(15))
    return park
def emp():
    emp=random.choice(["50+","below_50", "100+"], p=[0.2, 0.5, 0.3], size=(15))
    return emp
name=name()
month=month()
price=unitprice()
Q=quan()
L=location()
cid=coustomerid()
pid=prodid()
sid=storeid()
storesize=storesize()
closetime=closetime()
a=adv()#advertisement
c=com()#competetor price
supply=sup()#supply
payment=paytype()
profit=profit()
feedb=feedback()
infra=infra()
parking=parking()
emp=emp()
frame = {
    "StoreID": sid,
    "StoreSize": storesize,
    "Parking": parking,
    "ClosingTime": closetime,
    "Month": month,
    "CustomerID": cid,
    "ProductID": pid,
    "UnitPrice": price,
    "Quantity": Q,
    "CompetitorPrice": c,
    "Supply": supply,
    "Profit_percentage": profit,
    "Advertisementstar": a,
    "PaymentType": payment,
    "Employee": emp,
    "Feedbackstar": feedb
}
dfsales=pd.DataFrame(frame)
print(dfsales)
dfsales.to_excel('sales1.xlsx', index=False)

    StoreID      StoreSize       Parking  ClosingTime  Month  CustomerID  \
0      1316  Valueformoney     Available           23     12         313   
1      1308         Retail     Available           20     12         316   
2      1308        Economy      Spacious           20      4         313   
3      1310        Economy     Available           20     12         317   
4      1308        Premium      Spacious           20      2         308   
5      1303        Premium     Available           20      5         310   
6      1308  Factoryoutlet      Spacious           20      3         317   
7      1315         Retail  NotAvailable           21      4         303   
8      1313  Factoryoutlet      Spacious           20      6         318   
9      1312  Valueformoney      Spacious           20      7         316   
10     1302        Economy     Available           20      9         313   
11     1308  Valueformoney      Spacious           20      4         300   
12     1317 